<?php

namespace App\Services;

use App\Models\Sale;
use horstoeko\zugferd\ZugferdDocumentBuilder;
use horstoeko\zugferd\ZugferdProfiles;
use Tiime\FacturX\FacturX;

class FacturXService
{
    /**
     * Generate a Factur-X PDF (PDF/A-3 with XML) from a Sale and existing PDF content.
     *
     * @param Sale $sale
     * @param string $pdfContent The raw content of the PDF generated by DomPDF
     * @param bool $sign Apply digital signature (requires certificate configured)
     * @return string The raw content of the Factur-X PDF
     */
    public function generate(Sale $sale, string $pdfContent, bool $sign = false): string
    {
        // 1. Generate the XML (CII)
        $xmlContent = $this->generateXml($sale);

        // 2. Merge PDF and XML into PDF/A-3 Factur-X
        try {
            $facturx = new FacturX($pdfContent, $xmlContent);
            $merged  = $facturx->getPdfContent();
        } catch (\Throwable $e) {
            $merged = $pdfContent;
        }

        // 3. Optional digital signature
        if ($sign) {
            $tmp = tempnam(sys_get_temp_dir(), 'facturx_') . '.pdf';
            file_put_contents($tmp, $merged);
            app(\App\Services\PdfSignatureService::class)->signPdf($tmp, [
                'name'   => $sale->company->name ?? config('app.name'),
                'reason' => 'Facture Factur-X — ' . ($sale->invoice_number ?? ''),
            ]);
            $merged = file_get_contents($tmp);
            @unlink($tmp);
        }

        return $merged;
    }

    /**
     * Generate the Factur-X XML (CII format) for a Sale.
     * Public so it can be used for preview.
     */
    public function generateXml(Sale $sale): string
    {
        // Create a new ZUGFeRD document (Basic Profile)
        $document = ZugferdDocumentBuilder::createNew(ZugferdProfiles::PROFILE_BASIC);

        $company = $sale->company;
        $customer = $sale->customer;

        // Document Information
        $typeCode = $sale->type === 'credit_note' ? '381' : '380';
        
        $document->setDocumentInformation(
            $sale->invoice_number,
            $typeCode, // 380 = Commercial Invoice, 381 = Credit Note
            $sale->created_at,
            $company->currency ?? "XOF" // Currency Code
        );

        // Seller Information (Company)
        $document->setDocumentSeller($company->name ?? 'Unknown Seller');
        $document->setDocumentSellerAddress(
            $company->address ?? '',
            null,
            null,
            $company->zip_code ?? '',
            $company->city ?? '',
            $company->country_code ?? 'SN'
        );
        if ($company->tax_number) {
            $document->addDocumentSellerTaxNumber($company->tax_number);
        }
        if ($company->siret ?? $company->registration_number) {
            $document->setDocumentSellerLegalOrganisation(
                $company->siret ?? $company->registration_number,
                '0002',
                $company->name ?? ''
            );
        }

        // Buyer Information (Customer)
        if ($customer) {
            $document->setDocumentBuyer($customer->name);
            $document->setDocumentBuyerAddress(
                $customer->address ?? '',
                null,
                null,
                $customer->zip_code ?? '',
                $customer->city ?? '',
                $customer->country_code ?? 'SN'
            );
        } else {
            $document->setDocumentBuyer("Client Comptant");
        }

        // Delivery address (if different from billing)
        if ($sale->delivery_address) {
            $document->setDocumentShipTo($customer->name ?? 'Client');
            $document->setDocumentShipToAddress(
                $sale->delivery_address,
                null,
                null,
                '',
                '',
                $customer->country_code ?? $company->country_code ?? 'FR'
            );
        }

        // Line Items — use per-line VAT rate instead of global tax_percent
        $lineNumber = 1;
        foreach ($sale->items as $item) {
            $document->addNewPosition((string) $lineNumber);
            $document->setDocumentPositionProductDetails(
                $item->product->name ?? 'Article',
                $item->product->description ?? null
            );
            // Pour Factur-X, les prix doivent être positifs même pour un avoir (le code 381 suffit)
            $document->setDocumentPositionNetPrice(abs($item->unit_price_ht ?? $item->unit_price));
            $unitCode = match(strtolower($item->unit ?? '')) {
                'h', 'heure', 'heures', 'hr'     => 'HUR',
                'kg', 'kilo'                      => 'KGM',
                'l', 'litre', 'litres'            => 'LTR',
                'm', 'metre', 'mètre'             => 'MTR',
                'm2', 'm²'                        => 'MTK',
                'j', 'jour', 'jours', 'day'       => 'DAY',
                'mois', 'month'                   => 'MON',
                default                           => 'H87',
            };
            $document->setDocumentPositionQuantity($item->quantity, $unitCode);
            $itemVatRate = $item->vat_rate ?? $sale->tax_percent ?? 0;
            $itemCategory = $item->vat_category ?? ($itemVatRate > 0 ? 'S' : 'E');
            $document->addDocumentPositionTax($itemCategory, "VAT", $itemVatRate);
            $lineNumber++;
        }

        // Totals — use per-rate VAT breakdown
        $vatBreakdown = $sale->getVatBreakdown();
        $subtotal = abs($sale->items->sum('total_price_ht'));
        $discountAmount = $subtotal * (($sale->discount_percent ?? 0) / 100);
        $basisAmount = $subtotal - $discountAmount;
        $totalTax = 0;

        // Tax Summary per rate
        foreach ($vatBreakdown as $vat) {
            $category = $vat['category'] ?? ($vat['rate'] > 0 ? 'S' : 'E');
            $document->addDocumentTax($category, "VAT", abs($vat['base']), abs($vat['amount']), $vat['rate']);
            $totalTax += abs($vat['amount']);
        }

        $grandTotal = abs($sale->total ?? ($basisAmount + $totalTax));

        // Moyen de paiement (obligatoire EN16931)
        $paymentMeansCode = match($sale->payment_method ?? 'transfer') {
            'transfer', 'virement'  => '30',
            'check', 'cheque'       => '10',
            'card', 'carte'         => '48',
            'direct_debit'          => '49',
            'cash', 'especes'       => '10',
            default                 => '30',
        };
        $document->addDocumentPaymentMean($paymentMeansCode);

        // Échéance
        $dueDate = $sale->due_date ?? $sale->created_at->copy()->addDays(30);
        $document->addDocumentPaymentTerm(null, $dueDate instanceof \Carbon\Carbon ? $dueDate : \Carbon\Carbon::parse($dueDate));

        // Document Summation
        $document->setDocumentSummation(
            $grandTotal,      // Grand total
            $grandTotal,      // Due payable
            $subtotal,        // Line total
            0,                // Charge total
            $discountAmount,  // Allowance total
            $basisAmount,     // Tax basis total
            $totalTax,        // Tax total
            null,             // Round amount
            0                 // Total prepaid
        );

        return $document->getContent();
    }
}
