<?php

namespace App\Services;

use App\Models\Sale;
use horstoeko\zugferd\ZugferdDocumentBuilder;
use horstoeko\zugferd\ZugferdProfiles;
use Tiime\FacturX\FacturX;

class FacturXService
{
    /**
     * Generate a Factur-X PDF (PDF/A-3 with XML) from a Sale and existing PDF content.
     *
     * @param Sale $sale
     * @param string $pdfContent The raw content of the PDF generated by DomPDF
     * @return string The raw content of the Factur-X PDF
     */
    public function generate(Sale $sale, string $pdfContent): string
    {
        // 1. Generate the XML (CII)
        $xmlContent = $this->generateXml($sale);

        // 2. Merge PDF and XML
        try {
            $facturx = new FacturX($pdfContent, $xmlContent);
            return $facturx->getPdfContent();
        } catch (\Throwable $e) {
            // Fallback: return original PDF if merging fails (e.g. PDF parsing issue)
            // Log error if needed
            return $pdfContent;
        }
    }

    /**
     * Generate the Factur-X XML (CII format) for a Sale.
     * Public so it can be used for preview.
     */
    public function generateXml(Sale $sale): string
    {
        // Create a new ZUGFeRD document (Basic Profile)
        $document = ZugferdDocumentBuilder::createNew(ZugferdProfiles::PROFILE_BASIC);

        $company = $sale->company;
        $customer = $sale->customer;

        // Document Information
        $typeCode = $sale->type === 'credit_note' ? '381' : '380';
        
        $document->setDocumentInformation(
            $sale->invoice_number,
            $typeCode, // 380 = Commercial Invoice, 381 = Credit Note
            $sale->created_at,
            $company->currency ?? "XOF" // Currency Code
        );

        // Seller Information (Company)
        $document->setDocumentSeller($company->name ?? 'Unknown Seller');
        $document->setDocumentSellerAddress(
            $company->address ?? '',
            null,
            null,
            $company->zip_code ?? '',
            $company->city ?? '',
            $company->country_code ?? 'SN'
        );
        if ($company->tax_number) {
            $document->addDocumentSellerTaxNumber($company->tax_number);
        }

        // Buyer Information (Customer)
        if ($customer) {
            $document->setDocumentBuyer($customer->name);
            $document->setDocumentBuyerAddress(
                $customer->address ?? '',
                null,
                null,
                $customer->zip_code ?? '',
                $customer->city ?? '',
                $customer->country_code ?? 'SN'
            );
        } else {
            $document->setDocumentBuyer("Client Comptant");
        }

        // Delivery address (if different from billing)
        if ($sale->delivery_address) {
            $document->setDocumentShipTo($customer->name ?? 'Client');
            $document->setDocumentShipToAddress(
                $sale->delivery_address,
                null,
                null,
                '',
                '',
                $customer->country_code ?? $company->country_code ?? 'FR'
            );
        }

        // Line Items — use per-line VAT rate instead of global tax_percent
        $lineNumber = 1;
        foreach ($sale->items as $item) {
            $document->addNewPosition((string) $lineNumber);
            $document->setDocumentPositionProductDetails(
                $item->product->name ?? 'Article',
                $item->product->description ?? null
            );
            // Pour Factur-X, les prix doivent être positifs même pour un avoir (le code 381 suffit)
            $document->setDocumentPositionNetPrice(abs($item->unit_price_ht ?? $item->unit_price));
            $document->setDocumentPositionQuantity($item->quantity, "H87"); // H87 = Piece
            $itemVatRate = $item->vat_rate ?? $sale->tax_percent ?? 0;
            $itemCategory = $item->vat_category ?? ($itemVatRate > 0 ? 'S' : 'E');
            $document->addDocumentPositionTax($itemCategory, "VAT", $itemVatRate);
            $lineNumber++;
        }

        // Totals — use per-rate VAT breakdown
        $vatBreakdown = $sale->getVatBreakdown();
        $subtotal = abs($sale->items->sum('total_price_ht'));
        $discountAmount = $subtotal * (($sale->discount_percent ?? 0) / 100);
        $basisAmount = $subtotal - $discountAmount;
        $totalTax = 0;

        // Tax Summary per rate
        foreach ($vatBreakdown as $vat) {
            $category = $vat['category'] ?? ($vat['rate'] > 0 ? 'S' : 'E');
            $document->addDocumentTax($category, "VAT", abs($vat['base']), abs($vat['amount']), $vat['rate']);
            $totalTax += abs($vat['amount']);
        }

        $grandTotal = abs($sale->total ?? ($basisAmount + $totalTax));

        // Document Summation
        $document->setDocumentSummation(
            $grandTotal,      // Grand total
            $grandTotal,      // Due payable
            $subtotal,        // Line total
            0,                // Charge total
            $discountAmount,  // Allowance total
            $basisAmount,     // Tax basis total
            $totalTax,        // Tax total
            null,             // Round amount
            0                 // Total prepaid
        );

        return $document->getContent();
    }
}
